// @ts-nocheck
import { Audio } from "./audio";
import { Bugs, MAX_BUGS } from "./bugs";
import { Effects } from "./effects";

(() => {
'use strict';
let LANG='es';
const I18N={es:{hammer:'Martillo',flame:'Lanzallamas',spray:'Insecticida',gun:'Ametralladora',reset:'Reset',start:'Iniciar',tests:'Tests',vector:'Vector',audio:'Audio',register:'Registro',tool:'Herramienta',export:'Exportar',k_h:'martillo',k_f:'lanzallamas',k_i:'insecticida',k_g:'ametralladora',k_r:'reset',bugs:'Bichos',intro_title:'Zé Bocha dice: piensa como estratega (modo taurino)',intro_body:'Zé Bocha te reta: cada bicho representa una <b>tarea pendiente del mundo adulto</b>. Los cuatro tamaños equivalen a <i>Chori · Novillo · Bravío · Torazo</i>. Tu faena es priorizar como estratega, elegir la herramienta adecuada y rematar la arena: <b>matar todos los bugs</b> lo más rápido posible para recuperar el control de tu tiempo. Los bugs Bravío tienen la habilidad de engendrar nuevos choris cada 3 segundos y los Torazo pueden <b>revivir bugs muertos</b> — si dejas de torear lo importante, la plaga de tareas se come tu tiempo de vida.',intro_goal:'Objetivo',intro_goal2:'matar a todos los bichos en el menor tiempo posible',intro_controls:'Controles',intro_tip:'Tip',intro_tip2:'prioriza Torazo y Bravío antes de swarms Chori',play:'Jugar',reg_title:'Registro de jugador (solo @zetabe.com)',name:'Nombre',country:'País',age:'Edad',gender:'Género',save:'Guardar',close:'Cerrar',legend_title:'Quién es quién',tier_chori:'Chori',tier_novillo:'Novillo',tier_bravio:'Bravío',tier_torazo:'Torazo',tier_chori_sub:'Rápido, débil; sin habilidad.',tier_novillo_sub:'Balanceado; sin habilidad especial.',tier_bravio_sub:'Engendra Chori cada 3 s (sin herida).',tier_torazo_sub:'Revive caídos cercanos (CD).',void:'Pantalla comida',lost_title:'¡Perdiste!',lost_body:'Los bugs se comieron demasiada pantalla. Vuelve a intentarlo con prioridad estratégica.',try_again:'Reintentar',bite_rate:'Velocidad mordida',pin:'Anclar'},pt:{hammer:'Martelo',flame:'Lança-chamas',spray:'Inseticida',gun:'Metralhadora',reset:'Reset',start:'Iniciar',tests:'Tests',vector:'Vetor',audio:'Áudio',register:'Registro',tool:'Ferramenta',export:'Exportar',k_h:'martelo',k_f:'lança-chamas',k_i:'inseticida',k_g:'metralhadora',k_r:'reset',bugs:'Insetos',intro_title:'Zé Bocha diz: pense como estrategista (modo touro)',intro_body:'Zé Bocha te desafia: cada inseto representa uma <b>tarefa pendente</b>. Os quatro tamanhos equivalem a <i>Chori · Novilho · Bravo · Torazão</i>. Sua faena é priorizar como estrategista, escolher a ferramenta certa e limpar a arena: <b>eliminar todos os bugs</b> o mais rápido possível para recuperar o controle do seu tempo. Os Bravo geram novos choris a cada 3 segundos e os Torazão podem <b>reviver bugs mortos</b> — se você parar de enfrentar o importante, a praga de tarefas come seu tempo de vida.',intro_goal:'Objetivo',intro_goal2:'Matar todos os bugs no menor tempo possível',intro_controls:'Controles',intro_tip:'Dica',intro_tip2:'priorize Torazão e Bravo antes dos swarms Chori',play:'Jogar',reg_title:'Registro do jogador (somente @zetabe.com)',name:'Nome',country:'País',age:'Idade',gender:'Gênero',save:'Salvar',close:'Fechar',legend_title:'Quem é quem',tier_chori:'Chori',tier_novillo:'Novilho',tier_bravio:'Bravo',tier_torazo:'Torazão',tier_chori_sub:'Rápido, fraco; sem habilidade.',tier_novillo_sub:'Equilibrado; sem habilidade especial.',tier_bravio_sub:'Gera Chori a cada 3 s (sem ferida).',tier_torazo_sub:'Revive caídos próximos (CD).',void:'Tela comida',lost_title:'Você perdeu!',lost_body:'Os bugs comeram uma parte grande da tela. Tente de novo com prioridade estratégica.',try_again:'Tentar novamente',bite_rate:'Velocidade de mordida',pin:'Fixar'}};
function applyI18N(){const d=I18N[LANG];
document.querySelectorAll('[data-i]').forEach(el=>{const k=el.getAttribute('data-i');
if(d[k])el.innerHTML=d[k]});
document.getElementById('langLabel').textContent=LANG.toUpperCase()}const $=s=>document.querySelector(s);
function dbg(m){try{const el=$('#debug');
if(!el)return;
el.style.display='block';
const t=new Date().toLocaleTimeString();
el.innerHTML=`<div>[${t}] ${m}</div>`+el.innerHTML}catch(e){}}window.onerror=(m,s,l)=>dbg('Error: '+m+' @'+l);
window.onunhandledrejection=e=>dbg('Rejection: '+e.reason);
const canvas=$('#game'),ctx=canvas.getContext('2d',{alpha:false});
const dpr=Math.max(1,Math.min(2,window.devicePixelRatio||1));
Effects.init();
const damageCanvas=document.createElement('canvas'),damageCtx=damageCanvas.getContext('2d');
const voidCanvas=document.createElement('canvas'),voidCtx=voidCanvas.getContext('2d');
let voidEstimate=0,LOST=false;
const VOID_LIMIT=0.5;
let W=0,H=0,last=0,fps=0;
let toolKey='h';
const TOOL_NAME_BY_KEY={h:'hammer',f:'flame',i:'spray',g:'gun'};
const TOOL_KEY_BY_NAME={hammer:'h',flame:'f',spray:'i',gun:'g'};
const pointer={x:0,y:0,down:false};
let vectorMode=false,shootCooldown=0;
let runStart=null,bestTime=null,WIN_SHOWN=false;
let EAT_RATE=0.6;
let audioCtx=null,masterGain=null,audioMuted=false,noiseBuf=null,flameNode=null,flameGain=null,sprayNode=null,sprayGain=null,comp=null;
const VOLUME_BOOST=3;
function ensureAudio(){if(audioCtx)return;
const AC=window.AudioContext||window.webkitAudioContext;
audioCtx=new AC;
masterGain=audioCtx.createGain();
masterGain.gain.value=audioMuted?0:.8*VOLUME_BOOST;
comp=audioCtx.createDynamicsCompressor();
comp.threshold.value=-10;
comp.knee.value=20;
comp.ratio.value=12;
comp.attack.value=.003;
comp.release.value=.25;
masterGain.connect(comp);
comp.connect(audioCtx.destination)}function makeNoiseBuffer(){if(noiseBuf)return noiseBuf;
const sr=audioCtx.sampleRate,len=sr*2,buf=audioCtx.createBuffer(1,len,sr),d=buf.getChannelData(0);
for(let i=0;
i<len;
i++)d[i]=Math.random()*2-1;
return noiseBuf=buf}function startFlameAudio(){if(audioMuted)return;
ensureAudio();
if(flameNode)return;
const src=audioCtx.createBufferSource();
src.buffer=makeNoiseBuffer();
src.loop=true;
const bp=audioCtx.createBiquadFilter();
bp.type='bandpass';
bp.frequency.value=520;
bp.Q.value=.9;
const lp=audioCtx.createBiquadFilter();
lp.type='lowpass';
lp.frequency.value=2400;
const gn=audioCtx.createGain();
gn.gain.value=0;
src.connect(bp);
bp.connect(lp);
lp.connect(gn);
gn.connect(masterGain);
src.start();
flameNode=src;
flameGain=gn;
const now=audioCtx.currentTime;
flameGain.gain.linearRampToValueAtTime(Math.min(.42*VOLUME_BOOST,2),now+.08)}function stopFlameAudio(){if(!audioCtx||!flameGain)return;
const now=audioCtx.currentTime;
flameGain.gain.cancelScheduledValues(now);
flameGain.gain.linearRampToValueAtTime(0,now+.08);
const s=flameNode;
setTimeout(()=>{try{s&&s.stop()}catch{}},140);
flameNode=null;
flameGain=null}function startSprayAudio(){if(audioMuted)return;
ensureAudio();
if(sprayNode)return;
const src=audioCtx.createBufferSource();
src.buffer=makeNoiseBuffer();
src.loop=true;
const bp=audioCtx.createBiquadFilter();
bp.type='bandpass';
bp.frequency.value=1100;
bp.Q.value=.9;
const lp=audioCtx.createBiquadFilter();
lp.type='lowpass';
lp.frequency.value=3200;
const gn=audioCtx.createGain();
gn.gain.value=0;
src.connect(bp);
bp.connect(lp);
lp.connect(gn);
gn.connect(masterGain);
src.start();
sprayNode=src;
sprayGain=gn;
const now=audioCtx.currentTime;
sprayGain.gain.linearRampToValueAtTime(Math.min(.42*VOLUME_BOOST,2),now+.08)}function stopSprayAudio(){if(!audioCtx||!sprayGain)return;
const now=audioCtx.currentTime;
sprayGain.gain.cancelScheduledValues(now);
sprayGain.gain.linearRampToValueAtTime(0,now+.06);
const s=sprayNode;
setTimeout(()=>{try{s&&s.stop()}catch{}},120);
sprayNode=null;
sprayGain=null}function playHammer(){if(audioMuted)return;
ensureAudio();
const n=audioCtx.createBufferSource();
n.buffer=makeNoiseBuffer();
const low=audioCtx.createBiquadFilter();
low.type='lowpass';
low.frequency.value=180;
const g=audioCtx.createGain();
g.gain.value=1.2*VOLUME_BOOST;
n.connect(low);
low.connect(g);
g.connect(masterGain);
const th=audioCtx.createOscillator();
th.type='sine';
th.frequency.value=75;
const tg=audioCtx.createGain();
tg.gain.value=.9*VOLUME_BOOST;
th.connect(tg);
tg.connect(masterGain);
const t=audioCtx.currentTime;
n.start();
th.start();
g.gain.exponentialRampToValueAtTime(.001,t+.12);
tg.gain.exponentialRampToValueAtTime(.0001,t+.15);
n.stop(t+.16);
th.stop(t+.18)}function playHammerEffect(){try{const fn=Audio&&Audio.playHammer;if(typeof fn==='function'){const src=Function.prototype.toString.call(fn).replace(/\s+/g,'');if(src!=='functionplayHammer(){}'){fn();return}}}catch(e){}
playHammer();}function playGun(){if(audioMuted)return;
ensureAudio();
const src=audioCtx.createBufferSource();
src.buffer=makeNoiseBuffer();
const bp=audioCtx.createBiquadFilter();
bp.type='bandpass';
bp.frequency.value=2200+Math.random()*800;
bp.Q.value=4;
const g=audioCtx.createGain();
g.gain.value=.6*VOLUME_BOOST;
src.connect(bp);
bp.connect(g);
g.connect(masterGain);
const t=audioCtx.currentTime;
src.start();
g.gain.exponentialRampToValueAtTime(.0001,t+.045);
src.stop(t+.05)}const ML='#FFE600',MP='#00B1EA';
function setBugCount(n){const count=Math.min(MAX_BUGS,n|0);
Bugs.spawnInitial(count);
Bugs.clampCap();
updateHUD()}function eatAt(x,y,r){voidCtx.save();
voidCtx.globalCompositeOperation='source-over';
voidCtx.fillStyle='#000';
voidCtx.beginPath();
voidCtx.arc(x,y,r,0,Math.PI*2);
voidCtx.fill();
voidCtx.restore();
const area=Math.PI*r*r,norm=area/(W*H);
voidEstimate=Math.min(1,voidEstimate+norm*.6)}function brandColor(b){return b.type==='chori'||b.type==='novillo'?ML:MP}function drawBug(b){ctx.save();
ctx.translate(b.x,b.y);
ctx.rotate(b.a);
const R=b.r;
ctx.beginPath();
if(b.type==='chori')ctx.ellipse(0,0,R*.9,R*.6,0,0,Math.PI*2);
else if(b.type==='novillo'){ctx.moveTo(-R*.8,-R*.5);
ctx.lineTo(R*.8,-R*.5);
ctx.arc(R*.8,0,R*.5,-Math.PI/2,Math.PI/2);
ctx.lineTo(-R*.8,R*.5);
ctx.arc(-R*.8,0,R*.5,Math.PI/2,-Math.PI/2);
ctx.closePath()}else if(b.type==='bravio')ctx.arc(0,0,R*.9,0,Math.PI*2);
else ctx.arc(0,0,R*.95,0,Math.PI*2);
if(b.dead)ctx.fillStyle='rgba(209,0,0,.75)';
else ctx.fillStyle='rgba(0,0,0,.15)';
ctx.fill();
ctx.lineJoin='round';
ctx.lineCap='round';
ctx.lineWidth=Math.max(3*dpr,3*dpr);
ctx.strokeStyle='rgba(255,255,255,.95)';
ctx.stroke();
ctx.lineWidth=Math.max(1.6*dpr,1.6*dpr);
ctx.strokeStyle=b.dead?'rgba(200,0,0,.95)':brandColor(b);
ctx.stroke();
if(b.type==='bravio'&&!b.dead){ctx.lineWidth=1.4*dpr;
ctx.strokeStyle=brandColor(b);
for(let i=0;
i<10;
i++){const a=i*(Math.PI*2/10);
ctx.beginPath();
ctx.moveTo(Math.cos(a)*R*.5,Math.sin(a)*R*.5);
ctx.lineTo(Math.cos(a)*R*1.6,Math.sin(a)*R*1.6);
ctx.stroke()}}if(b.type==='torazo'&&!b.dead){ctx.beginPath();
ctx.arc(0,0,R*1.5,0,Math.PI*2);
ctx.globalAlpha=.12;
ctx.strokeStyle='rgba(255,255,255,.9)';
ctx.lineWidth=1.2*dpr;
ctx.stroke();
ctx.globalAlpha=1}ctx.restore()}const h={name:'hammer',init(){},resetForRun(){},hitAt(x,y){Effects.spawnHit(x,y,{dpr});
playHammerEffect();
const R=46*dpr,grd=damageCtx.createRadialGradient(x,y,1,x,y,R);
grd.addColorStop(0,'rgba(40,40,45,.6)');
grd.addColorStop(1,'rgba(40,40,45,0)');
damageCtx.fillStyle=grd;
damageCtx.beginPath();
damageCtx.arc(x,y,R,0,Math.PI*2);
damageCtx.fill();
damageCtx.strokeStyle='rgba(20,20,30,.55)';
damageCtx.lineWidth=1.5*dpr;
for(let i=0;
i<12;
i++){const a=Math.random()*Math.PI*2,len=(40+Math.random()*90)*dpr;
damageCtx.beginPath();
damageCtx.moveTo(x,y);
damageCtx.lineTo(x+Math.cos(a)*len,y+Math.sin(a)*len);
damageCtx.stroke()}
Effects.addShake(3*dpr,120);
Bugs.hitAt(x,y,'hammer');},getAll(){return[];}};function impactHammer(x,y){h.hitAt(x,y);}function burnAt(x,y,dt){Effects.spawnFlame(x,y,{dpr});
Bugs.hitAt(x,y,'flame',{dt});}function sprayAt(x,y,dt){Effects.spawnSpray(x,y,{dpr});
const R=130*dpr,g=damageCtx.createRadialGradient(x,y,8,x,y,R);
g.addColorStop(0,'rgba(80,255,120,.12)');
g.addColorStop(1,'rgba(80,255,120,0)');
damageCtx.save();
damageCtx.globalCompositeOperation='lighter';
damageCtx.fillStyle=g;
damageCtx.beginPath();
damageCtx.arc(x,y,R,0,Math.PI*2);
damageCtx.fill();
damageCtx.restore();
Bugs.hitAt(x,y,'spray',{dt});}function shootAt(x,y){playGun();
damageCtx.save();
damageCtx.globalCompositeOperation='destination-out';
damageCtx.beginPath();
damageCtx.arc(x,y,4.2*dpr,0,Math.PI*2);
damageCtx.fill();
damageCtx.restore();
Effects.spawnGun(x,y,{dpr});
Effects.addShake(3*dpr,60);
Bugs.hitAt(x,y,'gun');}
const f={name:'flame',init(){},resetForRun(){stopFlameAudio();},start(){startFlameAudio();},stop(){stopFlameAudio();},hitAt(x,y,dt=0){burnAt(x,y,dt);},getAll(){return[];}};
const i={name:'spray',init(){},resetForRun(){stopSprayAudio();},start(){startSprayAudio();},stop(){stopSprayAudio();},hitAt(x,y,dt=0){sprayAt(x,y,dt);},getAll(){return[];}};
const g={name:'gun',init(){},resetForRun(){shootCooldown=0;},start(){},stop(){},hitAt(x,y){shootAt(x,y);},getAll(){return[];}};
const tools={h,f,i,g};
function currentToolObj(){return tools[toolKey]||h;}
function currentToolName(){return TOOL_NAME_BY_KEY[toolKey]||'hammer';}
if(typeof window!=='undefined'){window.h=h;window.f=f;window.i=i;window.g=g;}
function setTool(t){const prevTool=currentToolObj();
const prevKey=toolKey;
const nextKey=TOOL_KEY_BY_NAME[t]||'h';
const nextName=TOOL_NAME_BY_KEY[nextKey]||'hammer';
toolKey=nextKey;
if(prevTool&&prevKey!==nextKey&&typeof prevTool.stop==='function')prevTool.stop();
document.querySelectorAll('.btn[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===nextName));
updateHUD()}canvas.addEventListener('pointerdown',e=>{pointer.down=true;
updatePointer(e);
if(!runStart)return;
ensureAudio();
const tool=currentToolObj();
if(tool&&typeof tool.start==='function')tool.start();
if(toolKey==='h'||toolKey==='g')tool.hitAt(pointer.x,pointer.y)});
canvas.addEventListener('pointerup',()=>{pointer.down=false;
const tool=currentToolObj();
if(tool&&typeof tool.stop==='function')tool.stop()});
canvas.addEventListener('pointermove',e=>updatePointer(e));
function updatePointer(e){const sx=canvas.width/Math.max(1,canvas.clientWidth),sy=canvas.height/Math.max(1,canvas.clientHeight),rect=canvas.getBoundingClientRect(),ox=e.offsetX!==undefined?e.offsetX:e.clientX-rect.left,oy=e.offsetY!==undefined?e.offsetY:e.clientY-rect.top;
pointer.x=ox*sx;
pointer.y=oy*sy}window.addEventListener('keydown',e=>{const k=(e.key||'').toLowerCase();
if(k==='h')setTool('hammer');
else if(k==='f')setTool('flame');
else if(k==='i')setTool('spray');
else if(k==='g')setTool('gun');
else if(k==='r')doReset();
else if(k==='m'){const guideEl=document.getElementById('guidePanel'),legendEl=document.getElementById('legend');
[guideEl,legendEl].forEach(el=>{if(!el)return;
el.style.display=el.style.display==='none'?'':'none'})}else if(k==='v'){const hudEl=document.getElementById('hud'),guideEl=document.getElementById('guidePanel'),legendEl=document.getElementById('legend');
[hudEl,guideEl,legendEl].forEach(el=>{if(!el)return;
el.style.display=el.style.display==='none'?'':'none'})}});
Array.from(document.querySelectorAll('.btn[data-tool]')).forEach(btn=>btn.addEventListener('click',()=>setTool(btn.dataset.tool)));
const muteBtn=$('#muteBtn');
function syncMuteBtn(){muteBtn.classList.toggle('active',!audioMuted);
muteBtn.querySelector('[data-i="audio"]').textContent=I18N[LANG].audio}muteBtn.addEventListener('click',()=>{audioMuted=!audioMuted;
if(masterGain)masterGain.gain.value=audioMuted?0:.8*VOLUME_BOOST;
syncMuteBtn()});
const bugRange=$('#bugCount'),bugVal=$('#bugCountVal');
if(bugRange){bugVal.textContent=bugRange.value;
bugRange.addEventListener('input',()=>{let v=parseInt(bugRange.value);
if(v>MAX_BUGS){v=MAX_BUGS;
bugRange.value=v}bugVal.textContent=v;
setBugCount(v)})}const eatRange=$('#eatRate'),eatVal=$('#eatRateVal');
if(eatRange){const sync=()=>{EAT_RATE=+eatRange.value;
eatVal.textContent='x'+EAT_RATE.toFixed(2)};
sync();
eatRange.addEventListener('input',sync)}(function(){function paintBackground(){ctx.fillStyle='rgb(100,103,110)';
ctx.fillRect(0,0,W,H)}function resetDamageLayer(){damageCtx.setTransform(1,0,0,1,0,0);
damageCtx.clearRect(0,0,damageCanvas.width,damageCanvas.height)}function resetVoidLayer(){voidCtx.setTransform(1,0,0,1,0,0);
voidCtx.clearRect(0,0,voidCanvas.width,voidCanvas.height);
voidEstimate=0}function resize(){const r=dpr;
W=Math.floor(canvas.clientWidth*r);
H=Math.floor(canvas.clientHeight*r);
canvas.width=W;
canvas.height=H;
damageCanvas.width=W;
damageCanvas.height=H;
voidCanvas.width=W;
voidCanvas.height=H}window.addEventListener('resize',resize);
function boot(){try{applyI18N();
resize();
Bugs.init({dpr,getBounds:()=>({width:W,height:H}),getEatRate:()=>EAT_RATE,onBugEat:(x,y,r)=>eatAt(x,y,r),onBugKilled:handleBugKilled,onBugRevived:handleBugRevived,onBravioSpawn:(x,y)=>Effects.spawnFlame(x,y,{dpr}),onTorazoRevive:b=>Effects.spawnFlame(b.x,b.y,{dpr,mode:'revive'})});
const bc=document.getElementById('bugCount');
const initial=bc?parseInt(bc.value)||100:100;
setBugCount(initial);
updateHUD();
dbg('Boot OK • spawn '+Bugs.getAll().length);
requestAnimationFrame(step)}catch(e){dbg('Boot ERR '+e.message)}}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);
else boot();
window.paintBackground=paintBackground;
window.resetDamageLayer=resetDamageLayer;
window.resetVoidLayer=resetVoidLayer;
window.resize=resize})();
$('#resetBtn').addEventListener('click',doReset);
$('#startBtn').addEventListener('click',()=>{const intro=$('#intro');
if(intro)intro.style.display='none';
doReset();
startRun();
});
$('#testBtn').addEventListener('click',runSelfTests);
$('#langBtn').addEventListener('click',()=>{LANG=LANG==='es'?'pt':'es';
applyI18N();
updateHUD()});
$('#regBtn').addEventListener('click',()=>showReg(true));
$('#exportBtn').addEventListener('click',()=>exportResults());
$('#tryAgain').addEventListener('click',()=>{document.getElementById('lost').style.display='none';
doReset();
startRun()});
function updateHUD(){const dict=I18N[LANG];
const activeToolName=currentToolName();
const toolLabel=({hammer:dict.hammer,flame:dict.flame,spray:dict.spray,gun:dict.gun}[activeToolName])||dict.hammer;
$('#statTool').textContent=(I18N[LANG].tool||'Herramienta')+': '+toolLabel;
const list=Bugs.getAll();
const aliveList=list.filter(b=>!b.dead);
$('#statBugs').textContent=(dict.bugs||'Bichos')+': '+aliveList.length;
$('#statDead').textContent='Muertos: '+Bugs.countDead();
const t=runStart?((performance.now()-runStart)/1000):0;
$('#statTime').textContent='Tiempo: '+t.toFixed(1)+'s';
if(runStart&&!LOST&&!WIN_SHOWN){checkWinState();}
$('#statVoid').innerHTML=`<span data-i="void">${dict.void||'Pantalla comida'}</span>: ${Math.round(voidEstimate*100)}%`;
const counts={chori:0,novillo:0,bravio:0,torazo:0};
for(const b of aliveList){if(counts[b.type]!==undefined)counts[b.type]++}$('#cnt_chori').textContent=counts.chori;
$('#cnt_novillo').textContent=counts.novillo;
$('#cnt_bravio').textContent=counts.bravio;
$('#cnt_torazo').textContent=counts.torazo}
function checkWinState(){if(!runStart||LOST||WIN_SHOWN)return;
if(Bugs.countAlive()===0&&Bugs.countDead()>0){WIN_SHOWN=true;
const secs=(performance.now()-runStart)/1000;
const score=Bugs.countDead();
const msg=`Lo lograste, acabaste de pisotear a todos esos bichos; bien hecho; tu tiempo es de ${secs.toFixed(1)}s y tu puntuacion final es de ${score}`;
const el=document.getElementById('won');
const p=document.getElementById('winMsg');
if(p)p.textContent=msg;
if(el)el.style.display='flex';}}
function handleBugKilled(){checkWinState();
updateHUD()}
function handleBugRevived(){updateHUD()}
function doReset(){
LOST=false;
WIN_SHOWN=false;
try{document.getElementById('lost').style.display='none'}catch(e){}try{document.getElementById('won').style.display='none'}catch(e){}resetDamageLayer();
resetVoidLayer();
Effects.clear();
shootCooldown=0;
Object.values(tools).forEach(t=>{if(t&&typeof t.resetForRun==='function')t.resetForRun();});
Bugs.resetForRun();
runStart=null;
stopFlameAudio();
stopSprayAudio();
updateHUD()}let hudNext=0;

function step(ts){if(!last)last=ts;
const dt=Math.min(.033,(ts-last)/1000);
last=ts;
const inst=1/Math.max(.001,dt);
fps=fps?fps*.9+inst*.1:inst;
ctx.setTransform(1,0,0,1,0,0);
const {x:sx,y:sy}=Effects.getShakeOffset();
if(sx||sy)ctx.translate(sx,sy);
paintBackground();
const bugList=Bugs.getAll();
if(!runStart){Effects.update(dt);
ctx.drawImage(damageCanvas,0,0);
ctx.drawImage(voidCanvas,0,0);
for(const b of bugList)drawBug(b);
$('#statFps').textContent='FPS: '+Math.round(fps);
if(ts>=hudNext){updateHUD();
hudNext=ts+100;}
requestAnimationFrame(step);
return}const tool=currentToolObj();
if(pointer.down&&toolKey==='f')tool.hitAt(pointer.x,pointer.y,dt);
if(pointer.down&&toolKey==='i')tool.hitAt(pointer.x,pointer.y,dt);
if(pointer.down&&toolKey==='g'){shootCooldown-=dt;
if(shootCooldown<=0){tool.hitAt(pointer.x,pointer.y);
shootCooldown=.045;}}
Bugs.update(dt);
ctx.drawImage(damageCanvas,0,0);
ctx.drawImage(voidCanvas,0,0);
Effects.update(dt);
const particles=Effects.getParticles();
for(const p of particles){const t=p.age/p.life,r=p.size*(1-.7*t);
if(p.type==='flame'){ctx.globalCompositeOperation='lighter';
ctx.fillStyle=flameColor(t)}else if(p.type==='ember'){ctx.globalCompositeOperation='lighter';
ctx.fillStyle=emberColor(p.tone,t)}else if(p.type==='toxic'){ctx.globalCompositeOperation='lighter';
ctx.fillStyle='rgba(120,255,120,'+(.85*(1-t)+.05)+')'}else{ctx.globalCompositeOperation='source-over';
ctx.fillStyle='rgba(255,255,255,'+(1-t)+')'}ctx.beginPath();
ctx.arc(p.x,p.y,r,0,Math.PI*2);
ctx.fill();
ctx.globalCompositeOperation='source-over'}
const activeBugs=Bugs.getAll();
for(const b of activeBugs)drawBug(b);
const alive=Bugs.countAlive()>0;
if(runStart&&voidEstimate>=VOID_LIMIT&&!LOST){LOST=true;
runStart=null;
pointer.down=false;
stopFlameAudio();
stopSprayAudio();
document.getElementById('lost').style.display='flex';}
if(runStart&&!alive){const elapsed=(performance.now()-runStart)/1000;
if(bestTime==null||elapsed<bestTime){bestTime=elapsed;
saveBest(elapsed);}runStart=null;}
$('#statFps').textContent='FPS: '+Math.round(fps);
if(ts>=hudNext){updateHUD();
hudNext=ts+100;}
requestAnimationFrame(step)}function flameColor(t){let r,g,b;
if(t<.25){const u=t/.25;
r=Math.floor(220+35*u);
g=Math.floor(230+25*u);
b=255}else if(t<.5){const u=(t-.25)/.25;
r=255;
g=Math.floor(255-20*u);
b=Math.floor(255-155*u)}else if(t<.75){const u=(t-.5)/.25;
r=255;
g=Math.floor(235-185*u);
b=Math.floor(100-60*u)}else{const u=(t-.75)/.25;
r=255;
g=Math.floor(50-30*u);
b=Math.floor(40-30*u)}const a=.9*(1-t)+.08;
return`rgba(${r},${g},${b},${a})`}function emberColor(tone,t){const a=.85*(1-t)+.06;
if(tone==='red')return`rgba(255,${60+Math.floor(40*(1-t))},${40+Math.floor(30*(1-t))},${a})`;
if(tone==='orange')return`rgba(255,${150+Math.floor(30*(1-t))},40,${a})`;
return`rgba(255,220,60,${a})`}function assert(c,m){dbg((c?'✅ ':'❌ ')+m)}function runSelfTests(){try{const before=currentToolName();
setTool('flame');
assert(currentToolName()==='flame','setTool ok');
setTool(before);
const want=100,bc=$('#bugCount');
if(bc){bc.value=want;
bc.dispatchEvent(new Event('input'));
assert(Bugs.getAll().length<=100,'cap 100')}else assert(false,'bugCount missing');
const p0=Effects.getParticles().length;
Effects.spawnFlame(100,100,{dpr});
assert(Effects.getParticles().length>p0,'particles added');
window.dispatchEvent(new KeyboardEvent('keydown',{key:'f'}));
assert(currentToolName()==='flame','key f');
window.dispatchEvent(new KeyboardEvent('keydown',{key:'h'}));
assert(currentToolName()==='hammer','key h');
const v0=voidEstimate;
eatAt(50,50,20*dpr);
assert(voidEstimate>v0,'void increases');
assert(validateEmail('a@zetabe.com'),'email ok');
assert(!validateEmail('a@other.com'),'email fail');
const prev=LANG;
$('#langBtn').click();
assert(document.getElementById('langLabel').textContent!==prev.toUpperCase(),'i18n toggle');
$('#langBtn').click();
dbg('Self-tests completados')}catch(e){dbg('Tests err '+e.message)}}$('#closeIntro').addEventListener('click',()=>{$('#intro').style.display='none';
startRun()});
function startRun(){try{document.getElementById('won').style.display='none';
document.getElementById('lost').style.display='none'}catch(e){}try{const list=Bugs.getAll();
if(!list.some(b=>b.type==='bravio')){Bugs.spawn('bravio',{x:canvas.width*0.5,y:canvas.height*0.5});
}}catch(e){}if(runStart)return;
runStart=performance.now()}function showReg(show){const modal=document.getElementById('regModal');
if(!modal)return;
modal.style.display=show?'flex':'none';
if(show){const p=loadProfile()||{};
const set=(id,val)=>{const el=document.getElementById(id);
if(el)el.value=val||''};
set('p_name',p.name);
set('p_email',p.email);
set('p_country',p.country||'MX');
set('p_age',p.age||'25-34');
set('p_gender',p.gender||'M');
const st=document.getElementById('regStatus');
if(st){const ok=validateEmail(p.email);
st.className='pill '+(ok?'ok':'warn');
st.textContent=ok?'✓ listo':'—'}}}function validateEmail(em){return/@zetabe\.com$/i.test(String(em||'').trim())}function loadProfile(){try{const a=localStorage.getItem('player');
const b=localStorage.getItem('dd_player');
return a?JSON.parse(a):(b?JSON.parse(b):null)}catch(e){return null}}function saveProfile(p){try{localStorage.setItem('player',JSON.stringify(p))}catch(e){}}const saveRegBtn=document.getElementById('saveReg');
if(saveRegBtn){saveRegBtn.addEventListener('click',()=>{const p={name:(document.getElementById('p_name')||{}).value||'',email:(document.getElementById('p_email')||{}).value||'',country:(document.getElementById('p_country')||{}).value||'MX',age:(document.getElementById('p_age')||{}).value||'',gender:(document.getElementById('p_gender')||{}).value||'M'};
const st=document.getElementById('regStatus');
if(!/^[^@]+@zetabe\.com$/i.test(p.email)){if(st){st.className='pill bad';
st.textContent='Email debe ser @zetabe.com'};
return}try{localStorage.setItem('dd_player',JSON.stringify(p));
localStorage.setItem('player',JSON.stringify(p));
if(st){st.className='pill ok';
st.textContent='Guardado'}}catch(e){}setTimeout(()=>{showReg(false);
try{document.getElementById('intro').style.display='flex'}catch(e){}},300)})}const closeRegBtn=document.getElementById('closeReg');
if(closeRegBtn){closeRegBtn.addEventListener('click',()=>showReg(false))}const GAS_URL='https://script.google.com/a/macros/zetabe.com/s/AKfycbxx43I1LFllPt8EP5IfLEABT7FY_F_zsBAMCqfQdJg32ItoJvJf1b837mNqKi6Lf1uM/exec';
async function saveBest(seconds){try{const p=loadProfile()||{};
if(!validateEmail(p.email)){dbg('saveBest: sin email @zetabe.com; no se envía');
return}const row={ts:new Date().toISOString(),time:+seconds.toFixed(2),country:p.country||'',age:p.age||'',gender:p.gender||'',email:p.email||'',name:p.name||''};
await fetch(GAS_URL,{method:'POST',mode:'no-cors',body:JSON.stringify(row)});
dbg('Score enviado')}catch(e){dbg('saveBest err '+e.message)}}function exportResults(){try{const data={bestTime,dead:Bugs.countDead(),when:new Date().toISOString(),lang:LANG};
const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});
const a=document.createElement('a');
a.href=URL.createObjectURL(blob);
a.download='zetabe_score.json';
a.click();
URL.revokeObjectURL(a.href)}catch(e){dbg('export err '+e.message)}}document.getElementById('pinGuideBtn')&&document.getElementById('pinGuideBtn').addEventListener('click',function(){var el=document.getElementById('guidePanel');
if(!el)return;
if(el.style.position==='fixed'){el.style.position='';
el.style.top='';
el.style.right='';
}else{el.style.position='fixed';
el.style.top='16px';
el.style.right='16px';
}});
document.getElementById('playAgain')&&document.getElementById('playAgain').addEventListener('click',()=>{const el=document.getElementById('won');
if(el)el.style.display='none';
doReset();
startRun();
});
document.getElementById('closeWin')&&document.getElementById('closeWin').addEventListener('click',()=>{const el=document.getElementById('won');
if(el)el.style.display='none';
});

  window.Game = window.Game || {};

})();

